apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-go
  namespace: echo-go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-go
  template:
    metadata:
      labels:
        app: echo-go
    spec:
      containers:
      - name: echo-go
        image: lirika13/echo-go:v1
        ports:
        - containerPort: 8000
        env:
        - name: AUTHOR
          value: lirika
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
